/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Utilidades.Utilidades;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Harpie
 */
public class datosTarjeta extends javax.swing.JFrame {

    /**
     * Creates new form datosTarjeta
     */
    public datosTarjeta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        edNombrePropietario = new javax.swing.JTextField();
        edMes = new javax.swing.JTextField();
        edAV = new javax.swing.JTextField();
        edCVV2 = new javax.swing.JTextField();
        btnIngresarPagoCredito = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        chkPagoAutomatico = new javax.swing.JCheckBox();
        edNumeroTarjeta = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lblTarjetaIcon = new javax.swing.JLabel();
        lblCheckTarjeta = new javax.swing.JLabel();
        lblCheckFecha = new javax.swing.JLabel();
        lblCheckCVV2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Datos de Pago Tarjeta de Credito");
        jLabel1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jLabel1ComponentAdded(evt);
            }
        });

        edNombrePropietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edNombrePropietarioActionPerformed(evt);
            }
        });

        edMes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                edMesFocusLost(evt);
            }
        });

        edAV.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                edAVFocusLost(evt);
            }
        });

        edCVV2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                edCVV2FocusLost(evt);
            }
        });

        btnIngresarPagoCredito.setText("Ingresar");

        jLabel2.setText("/");

        jLabel3.setText("Fecha:");

        jLabel4.setText("CVV:");

        jLabel5.setText("Nombre del propietario");

        chkPagoAutomatico.setText("Pago Automatico");
        chkPagoAutomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPagoAutomaticoActionPerformed(evt);
            }
        });

        edNumeroTarjeta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edNumeroTarjetaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                edNumeroTarjetaFocusLost(evt);
            }
        });
        edNumeroTarjeta.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                edNumeroTarjetaInputMethodTextChanged(evt);
            }
        });
        edNumeroTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edNumeroTarjetaActionPerformed(evt);
            }
        });
        edNumeroTarjeta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edNumeroTarjetaKeyTyped(evt);
            }
        });

        jLabel6.setText("Numero De Tarjeta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edNombrePropietario)
                            .addComponent(btnIngresarPagoCredito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(chkPagoAutomatico))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(5, 5, 5)
                                        .addComponent(edMes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(edAV, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblCheckFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(21, 21, 21)
                                        .addComponent(jLabel4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(edNumeroTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblTarjetaIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCheckTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(edCVV2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblCheckCVV2, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(10, 10, 10)
                .addComponent(edNombrePropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel6)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edNumeroTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCheckTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(edCVV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edAV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCheckCVV2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCheckFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(chkPagoAutomatico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnIngresarPagoCredito))
                    .addComponent(lblTarjetaIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Utilidades Utils = new Utilidades();

    private void chkPagoAutomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPagoAutomaticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkPagoAutomaticoActionPerformed

    private void edNombrePropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edNombrePropietarioActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_edNombrePropietarioActionPerformed

    private void edNumeroTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edNumeroTarjetaActionPerformed
           // TODO add your handling code here:
        
    }//GEN-LAST:event_edNumeroTarjetaActionPerformed

    private void edNumeroTarjetaInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_edNumeroTarjetaInputMethodTextChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_edNumeroTarjetaInputMethodTextChanged

    private void edNumeroTarjetaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edNumeroTarjetaKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_edNumeroTarjetaKeyTyped

    private void edNumeroTarjetaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edNumeroTarjetaFocusLost
        // TODO add your handling code here:

        if (edNumeroTarjeta.getText().length() > 1){
            ImageIcon cardPick = Utils.tarjetaLinkMaker(edNumeroTarjeta.getText());
            lblTarjetaIcon.setIcon(cardPick);
        }else{
            try {
                lblTarjetaIcon.setIcon(Utils.returnDefault());
            } catch (IOException ex) {
                Logger.getLogger(datosTarjeta.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        try {
            lblCheckTarjeta.setIcon(Utils.returnCheck(Utils.esValidoNumero(edNumeroTarjeta.getText())));
        } catch (IOException ex) {
            Logger.getLogger(datosTarjeta.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_edNumeroTarjetaFocusLost

    private void jLabel1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jLabel1ComponentAdded

    }//GEN-LAST:event_jLabel1ComponentAdded

    private void edNumeroTarjetaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edNumeroTarjetaFocusGained
        // TODO add your handling code here:
                // TODO add your handling code here:
            try{
                ImageIcon defaultPick = Utils.returnDefault();
                lblTarjetaIcon.setIcon(defaultPick);
            }catch(IOException e){
                    System.out.println("Error al cargar recurso");
            }
    }//GEN-LAST:event_edNumeroTarjetaFocusGained

    private void edMesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edMesFocusLost
        // TODO add your handling code here:
        if (edAV.getText().length() > 0){
            try {
                lblCheckFecha.setIcon(Utils.returnCheck(Utils.esValidoFecha(edAV.getText(), edMes.getText())));
            } catch (IOException ex) {
                Logger.getLogger(datosTarjeta.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_edMesFocusLost

    private void edCVV2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edCVV2FocusLost
        try {
            // TODO add your handling code here:
            lblCheckCVV2.setIcon(Utils.returnCheck(Utils.esValidoCVV2(edCVV2.getText(), edNumeroTarjeta.getText())));
        } catch (IOException ex) {
            Logger.getLogger(datosTarjeta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_edCVV2FocusLost

    private void edAVFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edAVFocusLost
        // TODO add your handling code here:
        if (edAV.getText().length() > 0){
            try {
                lblCheckFecha.setIcon(Utils.returnCheck(Utils.esValidoFecha(edAV.getText(), edMes.getText())));
            } catch (IOException ex) {
                Logger.getLogger(datosTarjeta.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_edAVFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(datosTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(datosTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(datosTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(datosTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new datosTarjeta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresarPagoCredito;
    private javax.swing.JCheckBox chkPagoAutomatico;
    private javax.swing.JTextField edAV;
    private javax.swing.JTextField edCVV2;
    private javax.swing.JTextField edMes;
    private javax.swing.JTextField edNombrePropietario;
    private javax.swing.JTextField edNumeroTarjeta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblCheckCVV2;
    private javax.swing.JLabel lblCheckFecha;
    private javax.swing.JLabel lblCheckTarjeta;
    private javax.swing.JLabel lblTarjetaIcon;
    // End of variables declaration//GEN-END:variables
}
