/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import Abstractos.Persona;
import Utilidades.Utilidades;
import java.sql.Date;
import javax.swing.JOptionPane;
import API.Genero;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Harpie
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }
    
    Genero genGetter = new Genero();
    Boolean esNombreValido = false;
    int ClienteGenero = 404;
    String Nombre;
    String RUT;
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TipoDePago = new javax.swing.ButtonGroup();
        tiempoPago = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        edNombreCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        edRUTCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        edTelefonoCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        edMailCliente = new javax.swing.JTextField();
        chkSocio = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        rbPagoPrescencial = new javax.swing.JRadioButton();
        rbPagoTelefonico = new javax.swing.JRadioButton();
        rbDiario = new javax.swing.JRadioButton();
        rbMensual = new javax.swing.JRadioButton();
        rbTrimestral = new javax.swing.JRadioButton();
        rbAnual = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        lblCheckNombreCliente = new javax.swing.JLabel();
        lblCheckRUTCliente = new javax.swing.JLabel();
        lblCheckTelefonoCliente = new javax.swing.JLabel();
        lblCheckMailCliente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre Del Cliente");

        edNombreCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                edNombreClienteFocusLost(evt);
            }
        });

        jLabel3.setText("Telefono Del Cliente");

        jLabel4.setText("Mail del Cliente");

        chkSocio.setText("¿Es Socio?");

        jLabel5.setText("RUT Del Cliente");

        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Medio De Pago");

        TipoDePago.add(rbPagoPrescencial);
        rbPagoPrescencial.setText("Pago presencial");
        rbPagoPrescencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPagoPrescencialActionPerformed(evt);
            }
        });

        TipoDePago.add(rbPagoTelefonico);
        rbPagoTelefonico.setText("Pago Telefonico");

        tiempoPago.add(rbDiario);
        rbDiario.setText("Pase Diaro");
        rbDiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDiarioActionPerformed(evt);
            }
        });

        tiempoPago.add(rbMensual);
        rbMensual.setText("Mensual");

        tiempoPago.add(rbTrimestral);
        rbTrimestral.setText("Trimestral");

        tiempoPago.add(rbAnual);
        rbAnual.setText("Anual");

        jLabel7.setText("Duracion De La Membresia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(edRUTCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(edTelefonoCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                                    .addComponent(edNombreCliente, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCheckNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCheckRUTCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCheckTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbPagoPrescencial)
                                .addGap(18, 18, 18)
                                .addComponent(rbPagoTelefonico))
                            .addComponent(chkSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbTrimestral)
                                    .addComponent(rbDiario))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbAnual)
                                    .addComponent(rbMensual))))
                        .addGap(54, 54, 54))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(edMailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCheckMailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkSocio)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rbPagoPrescencial)
                                    .addComponent(rbPagoTelefonico))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rbDiario)
                                    .addComponent(rbMensual))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rbTrimestral)
                                    .addComponent(rbAnual))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblCheckTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(edTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(35, 35, 35))
                                    .addComponent(edMailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCheckMailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCheckNombreCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(edNombreCliente))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCheckRUTCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edRUTCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbDiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDiarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbDiarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        RUT = edRUTCliente.getText();
        String Telefono = edTelefonoCliente.getText();
        String Mail = edMailCliente.getText();
        Utilidades verficadores = new Utilidades();
        Boolean esValidoRut = verficadores.esValidoRUT(RUT);
        Boolean esValidoTelefono = verficadores.esValidoTelefono(Telefono);
        Boolean esValidoMail = verficadores.esValidoCorreo(Mail);
        Boolean esCliente = chkSocio.isSelected();
        int radioChecked=15;
        if(rbDiario.isSelected()){
            radioChecked = 1;
        }else if(rbMensual.isSelected()){
            radioChecked = 2;
        }else if(rbTrimestral.isSelected()){
            radioChecked = 3;
        }else if(rbAnual.isSelected()){
            radioChecked = 4;
        }
        Persona nuevoCliente = null;
        Date tiempoCaducidad = verficadores.escogerMembresia(radioChecked);
        String presentadorFormateado = "";
        String nuevoClientePresentador = "";
        
        if (esValidoRut && esValidoTelefono && esValidoMail && Nombre.split("\\s+").length > 0){

            nuevoCliente = new Persona(Nombre, ClienteGenero , RUT, Telefono, Mail, esCliente);
            nuevoClientePresentador = "Se ha creado un nuevo cliente! \nNombre: %s\n Genero: %s\nRUT: %s\nMail: %s\nEs Cliente: %s\nTelefono: %s\n";
            presentadorFormateado = String.format(nuevoClientePresentador, Nombre, nuevoCliente.getGeneroString(),RUT, Mail, esCliente, Telefono );

            if (tiempoCaducidad != null){
                nuevoCliente.añadirMembresia(tiempoCaducidad);
                nuevoClientePresentador = "Se ha creado un nuevo cliente! \nNombre: %s\nGenero: %s\nRUT: %s\nMail: %s\nEs Cliente: %s\nTelefono: %s\nTiempo Caducidad Membresia: %s";
                presentadorFormateado = String.format(nuevoClientePresentador, Nombre, nuevoCliente.getGeneroString(), RUT, Mail, esCliente, Telefono,tiempoCaducidad );
            }
        }else if(esValidoRut == false){
            JOptionPane.showMessageDialog(null, "El Rut Ingresado No Es Valido");
            nuevoCliente = null;
        }else if(esValidoMail == false){
            JOptionPane.showMessageDialog(null, "El Mail Ingresado No Es Valido");
            nuevoCliente = null;
        }else if(esValidoTelefono == false){
            JOptionPane.showMessageDialog(null, "El Telefono Ingresado No es Valido");
            nuevoCliente = null;

        }
        if (nuevoCliente != null){
            JOptionPane.showMessageDialog(null, presentadorFormateado);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rbPagoPrescencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPagoPrescencialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbPagoPrescencialActionPerformed

    private void edNombreClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edNombreClienteFocusLost
        // TODO add your handling code here:
        Nombre = edNombreCliente.getText();
        try {
                ClienteGenero = genGetter.hacerConsulta(Nombre);
            } catch (Exception ex) {
                System.out.println("Error");
                        
            }
            if (ClienteGenero == 0 || ClienteGenero == 1){
                esNombreValido = true;
            }
        
    }//GEN-LAST:event_edNombreClienteFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.ButtonGroup TipoDePago;
    private javax.swing.JCheckBox chkSocio;
    private javax.swing.JTextField edMailCliente;
    private javax.swing.JTextField edNombreCliente;
    private javax.swing.JTextField edRUTCliente;
    private javax.swing.JTextField edTelefonoCliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblCheckMailCliente;
    private javax.swing.JLabel lblCheckNombreCliente;
    private javax.swing.JLabel lblCheckRUTCliente;
    private javax.swing.JLabel lblCheckTelefonoCliente;
    private javax.swing.JRadioButton rbAnual;
    private javax.swing.JRadioButton rbDiario;
    private javax.swing.JRadioButton rbMensual;
    private javax.swing.JRadioButton rbPagoPrescencial;
    private javax.swing.JRadioButton rbPagoTelefonico;
    private javax.swing.JRadioButton rbTrimestral;
    public static javax.swing.ButtonGroup tiempoPago;
    // End of variables declaration//GEN-END:variables
}
